### ISSUE TITLE
model_weight.pt

### ISSUE THREAD

**Issue by lfs119** [36041255/PtypeATPaseGenerator#1]
Hi, Thanks for your awesome work.   When I run example.py
![image](https://github.com/user-attachments/assets/d48bea03-0957-4c28-a5db-d75e7fd12d10)
Can your share it with google drive link or Zenodo.

**Comment by 36041255** [comment]
Thank you for your usage. I'm sorry for my negligence and I have uploaded the model to github. Hope it can help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "36041255/PtypeATPaseGenerator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月4日(星期一) 下午3:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[36041255/PtypeATPaseGenerator] model_weight.pt (Issue #1)





 
Hi, Thanks for your awesome work.   When I run example.py
 image.png (view on web)
